root/usr/bin/zcat: root/usr/bin/busybox
root/usr/bin/yes: root/usr/bin/busybox
root/usr/bin/xzcat: root/usr/bin/busybox
root/usr/bin/xxd: root/usr/bin/busybox
root/usr/bin/xargs: root/usr/bin/busybox
root/usr/bin/whoami: root/usr/bin/busybox
root/usr/bin/who: root/usr/bin/busybox
root/usr/bin/which: root/usr/bin/busybox
root/usr/bin/wget: root/usr/bin/busybox
root/usr/bin/wc: root/usr/bin/busybox
root/usr/bin/watchdog: root/usr/bin/busybox
root/usr/bin/watch: root/usr/bin/busybox
root/usr/bin/w: root/usr/bin/busybox
root/usr/bin/vlock: root/usr/bin/busybox
root/usr/bin/vi: root/usr/bin/busybox
root/usr/bin/vconfig: root/usr/bin/busybox
root/usr/bin/uuencode: root/usr/bin/busybox
root/usr/bin/uudecode: root/usr/bin/busybox
root/usr/bin/usleep: root/usr/bin/busybox
root/usr/bin/uptime: root/usr/bin/busybox
root/usr/bin/unzip: root/usr/bin/busybox
root/usr/bin/unxz: root/usr/bin/busybox
root/usr/bin/unlzop: root/usr/bin/busybox
root/usr/bin/unlzma: root/usr/bin/busybox
root/usr/bin/unlink: root/usr/bin/busybox
root/usr/bin/unix2dos: root/usr/bin/busybox
root/usr/bin/uniq: root/usr/bin/busybox
root/usr/bin/uname: root/usr/bin/busybox
root/usr/bin/uevent: root/usr/bin/busybox
root/usr/bin/udhcpc: root/usr/bin/busybox
root/usr/bin/ubirename: root/usr/bin/busybox
root/usr/bin/tty: root/usr/bin/busybox
root/usr/bin/ts: root/usr/bin/busybox
root/usr/bin/truncate: root/usr/bin/busybox
root/usr/bin/true: root/usr/bin/busybox
root/usr/bin/traceroute: root/usr/bin/busybox
root/usr/bin/tr: root/usr/bin/busybox
root/usr/bin/touch: root/usr/bin/busybox
root/usr/bin/top: root/usr/bin/busybox
root/usr/bin/time: root/usr/bin/busybox
root/usr/bin/tftp: root/usr/bin/busybox
root/usr/bin/test: root/usr/bin/busybox
root/usr/bin/telnet: root/usr/bin/busybox
root/usr/bin/tee: root/usr/bin/busybox
root/usr/bin/tc: root/usr/bin/busybox
root/usr/bin/tar: root/usr/bin/busybox
root/usr/bin/tail: root/usr/bin/busybox
root/usr/bin/syslogd: root/usr/bin/busybox
root/usr/bin/sysctl: root/usr/bin/busybox
root/usr/bin/sync: root/usr/bin/busybox
root/usr/bin/switch_root: root/usr/bin/busybox
root/usr/bin/swapon: root/usr/bin/busybox
root/usr/bin/swapoff: root/usr/bin/busybox
root/usr/bin/svok: root/usr/bin/busybox
root/usr/bin/svc: root/usr/bin/busybox
root/usr/bin/sulogin: root/usr/bin/busybox
root/usr/bin/su: root/usr/bin/busybox
root/usr/bin/stty: root/usr/bin/busybox
root/usr/bin/strings: root/usr/bin/busybox
root/usr/bin/stat: root/usr/bin/busybox
root/usr/bin/start-stop-daemon: root/usr/bin/busybox
root/usr/bin/sort: root/usr/bin/busybox
root/usr/bin/sleep: root/usr/bin/busybox
root/usr/bin/shred: root/usr/bin/busybox
root/usr/bin/sha512sum: root/usr/bin/busybox
root/usr/bin/sha3sum: root/usr/bin/busybox
root/usr/bin/sha256sum: root/usr/bin/busybox
root/usr/bin/sha1sum: root/usr/bin/busybox
root/usr/bin/setsid: root/usr/bin/busybox
root/usr/bin/setserial: root/usr/bin/busybox
root/usr/bin/setpriv: root/usr/bin/busybox
root/usr/bin/setlogcons: root/usr/bin/busybox
root/usr/bin/setkeycodes: root/usr/bin/busybox
root/usr/bin/setfattr: root/usr/bin/busybox
root/usr/bin/setconsole: root/usr/bin/busybox
root/usr/bin/setarch: root/usr/bin/busybox
root/usr/bin/seq: root/usr/bin/busybox
root/usr/bin/sed: root/usr/bin/busybox
root/usr/bin/runlevel: root/usr/bin/busybox
root/usr/bin/run-parts: root/usr/bin/busybox
root/usr/bin/run-init: root/usr/bin/busybox
root/usr/bin/route: root/usr/bin/busybox
root/usr/bin/rmdir: root/usr/bin/busybox
root/usr/bin/rm: root/usr/bin/busybox
root/usr/bin/resume: root/usr/bin/busybox
root/usr/bin/resize: root/usr/bin/busybox
root/usr/bin/reset: root/usr/bin/busybox
root/usr/bin/renice: root/usr/bin/busybox
root/usr/bin/reboot: root/usr/bin/busybox
root/usr/bin/realpath: root/usr/bin/busybox
root/usr/bin/readprofile: root/usr/bin/busybox
root/usr/bin/readlink: root/usr/bin/busybox
root/usr/bin/rdate: root/usr/bin/busybox
root/usr/bin/pwd: root/usr/bin/busybox
root/usr/bin/ps: root/usr/bin/busybox
root/usr/bin/printf: root/usr/bin/busybox
root/usr/bin/printenv: root/usr/bin/busybox
root/usr/bin/poweroff: root/usr/bin/busybox
root/usr/bin/pivot_root: root/usr/bin/busybox
root/usr/bin/pipe_progress: root/usr/bin/busybox
root/usr/bin/ping: root/usr/bin/busybox
root/usr/bin/pidof: root/usr/bin/busybox
root/usr/bin/patch: root/usr/bin/busybox
root/usr/bin/paste: root/usr/bin/busybox
root/usr/bin/passwd: root/usr/bin/busybox
root/usr/bin/partprobe: root/usr/bin/busybox
root/usr/bin/openvt: root/usr/bin/busybox
root/usr/bin/od: root/usr/bin/busybox
root/usr/bin/nuke: root/usr/bin/busybox
root/usr/bin/nslookup: root/usr/bin/busybox
root/usr/bin/nproc: root/usr/bin/busybox
root/usr/bin/nologin: root/usr/bin/busybox
root/usr/bin/nohup: root/usr/bin/busybox
root/usr/bin/nl: root/usr/bin/busybox
root/usr/bin/nice: root/usr/bin/busybox
root/usr/bin/netstat: root/usr/bin/busybox
root/usr/bin/nameif: root/usr/bin/busybox
root/usr/bin/mv: root/usr/bin/busybox
root/usr/bin/mt: root/usr/bin/busybox
root/usr/bin/mountpoint: root/usr/bin/busybox
root/usr/bin/more: root/usr/bin/busybox
root/usr/bin/mktemp: root/usr/bin/busybox
root/usr/bin/mkswap: root/usr/bin/busybox
root/usr/bin/mkpasswd: root/usr/bin/busybox
root/usr/bin/mknod: root/usr/bin/busybox
root/usr/bin/mkfifo: root/usr/bin/busybox
root/usr/bin/mke2fs: root/usr/bin/busybox
root/usr/bin/mkdosfs: root/usr/bin/busybox
root/usr/bin/mkdir: root/usr/bin/busybox
root/usr/bin/microcom: root/usr/bin/busybox
root/usr/bin/mesg: root/usr/bin/busybox
root/usr/bin/mdev: root/usr/bin/busybox
root/usr/bin/md5sum: root/usr/bin/busybox
root/usr/bin/makedevs: root/usr/bin/busybox
root/usr/bin/lzopcat: root/usr/bin/busybox
root/usr/bin/lzma: root/usr/bin/busybox
root/usr/bin/lzcat: root/usr/bin/busybox
root/usr/bin/lsusb: root/usr/bin/busybox
root/usr/bin/lsscsi: root/usr/bin/busybox
root/usr/bin/lspci: root/usr/bin/busybox
root/usr/bin/lsof: root/usr/bin/busybox
root/usr/bin/lsattr: root/usr/bin/busybox
root/usr/bin/ls: root/usr/bin/busybox
root/usr/bin/logname: root/usr/bin/busybox
root/usr/bin/login: root/usr/bin/busybox
root/usr/bin/logger: root/usr/bin/busybox
root/usr/bin/loadkmap: root/usr/bin/busybox
root/usr/bin/loadfont: root/usr/bin/busybox
root/usr/bin/ln: root/usr/bin/busybox
root/usr/bin/linuxrc: root/usr/bin/busybox
root/usr/bin/linux64: root/usr/bin/busybox
root/usr/bin/linux32: root/usr/bin/busybox
root/usr/bin/link: root/usr/bin/busybox
root/usr/bin/less: root/usr/bin/busybox
root/usr/bin/last: root/usr/bin/busybox
root/usr/bin/klogd: root/usr/bin/busybox
root/usr/bin/killall5: root/usr/bin/busybox
root/usr/bin/killall: root/usr/bin/busybox
root/usr/bin/kill: root/usr/bin/busybox
root/usr/bin/iptunnel: root/usr/bin/busybox
root/usr/bin/iprule: root/usr/bin/busybox
root/usr/bin/iproute: root/usr/bin/busybox
root/usr/bin/ipneigh: root/usr/bin/busybox
root/usr/bin/iplink: root/usr/bin/busybox
root/usr/bin/ipcs: root/usr/bin/busybox
root/usr/bin/ipcrm: root/usr/bin/busybox
root/usr/bin/ipaddr: root/usr/bin/busybox
root/usr/bin/ip: root/usr/bin/busybox
root/usr/bin/install: root/usr/bin/busybox
root/usr/bin/init: root/usr/bin/busybox
root/usr/bin/inetd: root/usr/bin/busybox
root/usr/bin/ifup: root/usr/bin/busybox
root/usr/bin/ifdown: root/usr/bin/busybox
root/usr/bin/ifconfig: root/usr/bin/busybox
root/usr/bin/id: root/usr/bin/busybox
root/usr/bin/i2ctransfer: root/usr/bin/busybox
root/usr/bin/i2cset: root/usr/bin/busybox
root/usr/bin/i2cget: root/usr/bin/busybox
root/usr/bin/i2cdump: root/usr/bin/busybox
root/usr/bin/i2cdetect: root/usr/bin/busybox
root/usr/bin/hwclock: root/usr/bin/busybox
root/usr/bin/hostname: root/usr/bin/busybox
root/usr/bin/hostid: root/usr/bin/busybox
root/usr/bin/hexedit: root/usr/bin/busybox
root/usr/bin/hexdump: root/usr/bin/busybox
root/usr/bin/head: root/usr/bin/busybox
root/usr/bin/hdparm: root/usr/bin/busybox
root/usr/bin/halt: root/usr/bin/busybox
root/usr/bin/gzip: root/usr/bin/busybox
root/usr/bin/gunzip: root/usr/bin/busybox
root/usr/bin/grep: root/usr/bin/busybox
root/usr/bin/getty: root/usr/bin/busybox
root/usr/bin/getopt: root/usr/bin/busybox
root/usr/bin/fuser: root/usr/bin/busybox
root/usr/bin/fstrim: root/usr/bin/busybox
root/usr/bin/fsfreeze: root/usr/bin/busybox
root/usr/bin/freeramdisk: root/usr/bin/busybox
root/usr/bin/free: root/usr/bin/busybox
root/usr/bin/fold: root/usr/bin/busybox
root/usr/bin/flock: root/usr/bin/busybox
root/usr/bin/find: root/usr/bin/busybox
root/usr/bin/fgrep: root/usr/bin/busybox
root/usr/bin/fdisk: root/usr/bin/busybox
root/usr/bin/fdformat: root/usr/bin/busybox
root/usr/bin/fdflush: root/usr/bin/busybox
root/usr/bin/fbset: root/usr/bin/busybox
root/usr/bin/false: root/usr/bin/busybox
root/usr/bin/fallocate: root/usr/bin/busybox
root/usr/bin/factor: root/usr/bin/busybox
root/usr/bin/expr: root/usr/bin/busybox
root/usr/bin/ether-wake: root/usr/bin/busybox
root/usr/bin/env: root/usr/bin/busybox
root/usr/bin/eject: root/usr/bin/busybox
root/usr/bin/egrep: root/usr/bin/busybox
root/usr/bin/echo: root/usr/bin/busybox
root/usr/bin/dumpkmap: root/usr/bin/busybox
root/usr/bin/du: root/usr/bin/busybox
root/usr/bin/dos2unix: root/usr/bin/busybox
root/usr/bin/dnsdomainname: root/usr/bin/busybox
root/usr/bin/dnsd: root/usr/bin/busybox
root/usr/bin/dirname: root/usr/bin/busybox
root/usr/bin/diff: root/usr/bin/busybox
root/usr/bin/df: root/usr/bin/busybox
root/usr/bin/devmem: root/usr/bin/busybox
root/usr/bin/deluser: root/usr/bin/busybox
root/usr/bin/delgroup: root/usr/bin/busybox
root/usr/bin/deallocvt: root/usr/bin/busybox
root/usr/bin/dd: root/usr/bin/busybox
root/usr/bin/dc: root/usr/bin/busybox
root/usr/bin/date: root/usr/bin/busybox
root/usr/bin/cut: root/usr/bin/busybox
root/usr/bin/crontab: root/usr/bin/busybox
root/usr/bin/crond: root/usr/bin/busybox
root/usr/bin/cp: root/usr/bin/busybox
root/usr/bin/cmp: root/usr/bin/busybox
root/usr/bin/clear: root/usr/bin/busybox
root/usr/bin/cksum: root/usr/bin/busybox
root/usr/bin/chvt: root/usr/bin/busybox
root/usr/bin/chrt: root/usr/bin/busybox
root/usr/bin/chroot: root/usr/bin/busybox
root/usr/bin/chown: root/usr/bin/busybox
root/usr/bin/chmod: root/usr/bin/busybox
root/usr/bin/chgrp: root/usr/bin/busybox
root/usr/bin/chattr: root/usr/bin/busybox
root/usr/bin/cat: root/usr/bin/busybox
root/usr/bin/bzcat: root/usr/bin/busybox
root/usr/bin/bunzip2: root/usr/bin/busybox
root/usr/bin/bc: root/usr/bin/busybox
root/usr/bin/basename: root/usr/bin/busybox
root/usr/bin/base64: root/usr/bin/busybox
root/usr/bin/awk: root/usr/bin/busybox
root/usr/bin/ash: root/usr/bin/busybox
root/usr/bin/arping: root/usr/bin/busybox
root/usr/bin/arp: root/usr/bin/busybox
root/usr/bin/arch: root/usr/bin/busybox
root/usr/bin/ar: root/usr/bin/busybox
root/usr/bin/adduser: root/usr/bin/busybox
root/usr/bin/addgroup: root/usr/bin/busybox
root/usr/bin/[[: root/usr/bin/busybox
root/usr/bin/[: root/usr/bin/busybox
root/usr/bin/fbsplash: root/usr/bin/busybox
root/usr/bin/cpio: root/usr/bin/busybox

root/usr/bin/sh: root/usr/bin/bash
root/usr/bin/modprobe: root/usr/bin/kmod
root/usr/bin/modinfo: root/usr/bin/kmod
root/usr/bin/depmod: root/usr/bin/kmod
root/usr/bin/insmod: root/usr/bin/kmod
root/usr/bin/rmmod: root/usr/bin/kmod
root/usr/bin/lsmod: root/usr/bin/kmod
root/usr/bin/fsck.ntfs: root/usr/bin/ntfsfix
root/usr/bin/mount.ntfs: root/usr/bin/ntfs-3g
root/usr/bin/mount.ntfs-3g: root/usr/bin/ntfs-3g
root/usr/bin/fsck.ext2: root/usr/bin/e2fsck
root/usr/bin/fsck.ext3: root/usr/bin/e2fsck
root/usr/bin/fsck.ext4: root/usr/bin/e2fsck
root/usr/bin/fsck.vfat: root/usr/bin/fsck.fat
root/usr/bin/fsck.fat32: root/usr/bin/fsck.fat
root/usr/bin/fsck.fat16: root/usr/bin/fsck.fat
root/usr/bin/fsck.fat12: root/usr/bin/fsck.fat
root/usr/bin/fsck.msdos: root/usr/bin/fsck.fat
root/usr/bin/btrfsck: root/usr/bin/btrfs
root/usr/bin/mkfs.ntfs: root/usr/bin/mkntfs
root/usr/bin/mount.lowntfs-3g: lowntfs-3g
root/usr/bin/mount.ntfs-3g: ntfs-3g
