name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requires packages
        run: sudo apt update&&sudo apt install autoconf libtool autopoint po4a pkgconf shtool meson cmake make gcc gcc-aarch64-linux-gnu rsync patch bison gperf cpio gzip xz-utils zstd lz4
      - name: Fetch submodules
        run: bash scripts/submodules.sh
      - name: Build initramfs
        run: make TARGET=aarch64-linux-gnu initramfs.cpio.gz
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: initramfs.cpio.gz
          path: ./initramfs.cpio.gz
